Shader "COA/Water"
{
    // Water for a camera 18-90 m up. From there rolling waves are invisible; what reads as ALIVE is, in order:
    // foam lapping along the shore, pale shallows over a deep centre, sun glitter that crawls, a slow swell.
    // Depth comes from the camera depth texture (URP asset: Depth Texture ON -- ConfigureQuality). No opaque texture,
    // so no refraction: not worth a full-screen copy at this height.
    // The swell is NOT defined here. WaterSurface.cs owns the three waves and pushes them as globals, so a boat can ask
    // C# for the same height the GPU draws (WaterSurface.HeightAt).
    Properties
    {
        _Noise ("Normal (RG) + height (B), tileable, generated by SceneKit", 2D) = "bump" {}
        _Shallow ("Shallow colour", Color) = (0.36, 0.72, 0.70, 1)
        _Deep ("Deep colour", Color) = (0.05, 0.22, 0.34, 1)
        _Sky ("Sky reflection", Color) = (0.62, 0.78, 0.92, 1)
        _FoamColor ("Foam", Color) = (0.95, 0.98, 1.0, 1)
        _ShallowAlpha ("Alpha at the waterline", Range(0, 1)) = 0.30
        _DeepAlpha ("Alpha when deep", Range(0, 1)) = 0.93
        _DepthRange ("Metres to full depth colour", Range(0.2, 6)) = 1.7
        _FoamWidth ("Foam reaches this depth (m)", Range(0.05, 2)) = 0.55
        _FoamFreq ("Foam bands per metre of depth", Range(1, 40)) = 13
        _FoamSpeed ("Foam speed", Range(0, 4)) = 1.15
        _NormalStrength ("Ripple strength", Range(0, 2)) = 0.55
        _Glitter ("Sun glitter", Range(0, 6)) = 2.4
    }
    SubShader
    {
        // below the border drape (Transparent-20): territory colour is drawn OVER the water
        Tags { "RenderType" = "Transparent" "Queue" = "Transparent-40" "RenderPipeline" = "UniversalPipeline" }
        Pass
        {
            Name "Water"
            Tags { "LightMode" = "UniversalForward" }
            Blend SrcAlpha OneMinusSrcAlpha
            ZWrite Off
            ZTest LEqual
            Cull Back

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile_fragment _ _SHADOWS_SOFT
            #pragma multi_compile_fog
            // a transparent surface cannot use screen-space shadows: there is no depth of ITS OWN to look them up with
            #define _SURFACE_TYPE_TRANSPARENT 1
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareDepthTexture.hlsl"

            TEXTURE2D(_Noise); SAMPLER(sampler_Noise);
            CBUFFER_START(UnityPerMaterial)
                float4 _Noise_ST; float4 _Shallow; float4 _Deep; float4 _Sky; float4 _FoamColor;
                float _ShallowAlpha; float _DeepAlpha; float _DepthRange; float _FoamWidth; float _FoamFreq; float _FoamSpeed;
                float _NormalStrength; float _Glitter;
            CBUFFER_END

            // globals, from WaterSurface.cs.  wave = (dir.x, dir.z, k = 2pi / wavelength, amplitude);  speed = rad/s
            float _WaterTime; float4 _WaterWaves[3]; float4 _WaterSpeeds;

            struct A { float4 pos : POSITION; };
            struct V { float4 pos : SV_POSITION; float3 wpos : TEXCOORD0; float eye : TEXCOORD1; float fog : TEXCOORD2; };

            V vert(A i)
            {
                V o; float3 w = TransformObjectToWorld(i.pos.xyz);
                for (int k = 0; k < 3; k++)
                    w.y += _WaterWaves[k].w * sin(dot(_WaterWaves[k].xy, w.xz) * _WaterWaves[k].z + _WaterSpeeds[k] * _WaterTime);
                o.wpos = w; o.pos = TransformWorldToHClip(w);
                o.eye = -TransformWorldToView(w).z; o.fog = ComputeFogFactor(o.pos.z);
                return o;
            }

            half4 frag(V i) : SV_Target
            {
                float t = _WaterTime;
                float3 view = normalize(GetWorldSpaceViewDir(i.wpos));

                // ---- how deep is the water under this pixel? (along the view ray, then made vertical)
                float2 suv = i.pos.xy / _ScaledScreenParams.xy;
                float sceneEye = LinearEyeDepth(SampleSceneDepth(suv), _ZBufferParams);
                float depth = max(0.0, (sceneEye - i.eye) * saturate(view.y));

                // ---- ripples: two layers of the same tileable map, sliding across each other
                float4 n1 = SAMPLE_TEXTURE2D(_Noise, sampler_Noise, i.wpos.xz * 0.085 + float2(0.021, 0.013) * t);
                float4 n2 = SAMPLE_TEXTURE2D(_Noise, sampler_Noise, i.wpos.xz * 0.190 + float2(-0.017, 0.029) * t);
                float2 g = ((n1.xy + n2.xy) - 1.0) * _NormalStrength;
                float3 n = normalize(float3(-g.x, 1.0, -g.y));
                float chop = n1.z * 0.6 + n2.z * 0.4;                                    // 0..1, for breaking things up

                // ---- body colour
                float d01 = saturate(depth / _DepthRange); d01 = d01 * d01 * (3.0 - 2.0 * d01);
                float3 col = lerp(_Shallow.rgb, _Deep.rgb, d01);
                float alpha = lerp(_ShallowAlpha, _DeepAlpha, d01);

                // ---- light. Shadows are SOFTENED: on water a building's shadow is a dimming, not a black hole.
                Light sun = GetMainLight(TransformWorldToShadowCoord(i.wpos));
                float shade = lerp(0.55, 1.0, sun.shadowAttenuation);
                float3 ambient = max(SampleSH(float3(0, 1, 0)), 0.0);
                col *= ambient + sun.color * saturate(dot(n, sun.direction)) * shade;

                // ---- the sky in it, more at grazing angles
                float fres = pow(1.0 - saturate(dot(n, view)), 4.0);
                col = lerp(col, _Sky.rgb * (ambient + sun.color * 0.6), fres * 0.65);

                // ---- glitter: a tight highlight, thresholded so it breaks into sparkles that crawl with the ripples
                float3 hv = normalize(sun.direction + view);
                float spec = pow(saturate(dot(n, hv)), 260.0);
                float sparkle = smoothstep(0.25, 0.75, spec) + spec * 0.35;
                col += sun.color * sparkle * _Glitter * sun.shadowAttenuation * saturate(d01 * 3.0 + 0.25);

                // ---- foam: bands that travel TOWARD the shore (phase rises with time, so a crest moves to smaller depth),
                //      broken up by the ripple map, fading out by _FoamWidth; plus a thin line that is always at the waterline
                float shore = 1.0 - saturate(depth / _FoamWidth);
                float band = sin(depth * _FoamFreq + t * _FoamSpeed + chop * 5.0);
                float foam = smoothstep(0.35, 0.85, band) * shore * shore * smoothstep(0.30, 0.62, chop + shore * 0.35);
                foam = max(foam, smoothstep(0.10, 0.015, depth) * (0.55 + 0.45 * chop));
                foam = saturate(foam);
                col = lerp(col, _FoamColor.rgb * (ambient + sun.color * shade), foam);
                alpha = max(alpha, foam * 0.92);

                alpha *= smoothstep(0.0, 0.02, depth);                                   // no hard line where the plane meets the sand
                col = MixFog(col, i.fog);
                return half4(col, alpha);
            }
            ENDHLSL
        }
    }
}
